/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arenaSol from "./Arena.sol";
export type { arenaSol };
import type * as arenaNftSol from "./ArenaNft.sol";
export type { arenaNftSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { SimpleDuel } from "./SimpleDuel";
