/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleDuelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ARENA_ACTIVATION_POINTS"
      | "MAX_FEE_PERCENT"
      | "MAX_USER_DEADLINE"
      | "POINTS_PER_DUEL"
      | "RESOLUTION_TIMELOCK"
      | "activateArenaWithPoints"
      | "adminCreateDuel"
      | "authorizeResolver"
      | "authorizedResolvers"
      | "bettingToken"
      | "bettingTokenDecimals"
      | "calculatePotentialGains"
      | "canActivateArena"
      | "claimGains"
      | "claimRefund"
      | "createDuel"
      | "duelArenaEligible"
      | "duelCreationFee"
      | "duels"
      | "emergencyWithdraw"
      | "executeResolution"
      | "fanToken"
      | "fanTokenBalanceSnapshot"
      | "fanTokenDecimals"
      | "fanTokenThreshold"
      | "gasAdvanceFee"
      | "gasFeeDebt"
      | "gasRelayer"
      | "getBettingToken"
      | "getDuelInfo"
      | "getFanToken"
      | "getGasFeeDebt"
      | "getOutcomePot"
      | "getPlatformFeePercent"
      | "getUserBets"
      | "getUserPoints"
      | "isDuelBalanced"
      | "manualGasRepayment"
      | "moderators"
      | "nextDuelId"
      | "owner"
      | "pause"
      | "paused"
      | "pendingResolutions"
      | "placeBet"
      | "platformFeePercent"
      | "pointsPerBetUnit"
      | "proposeResolution"
      | "renounceOwnership"
      | "setArenaEligible"
      | "setDuelCreationFee"
      | "setFanTokenThreshold"
      | "setGasAdvanceFee"
      | "setGasRelayer"
      | "setModerator"
      | "setPlatformFeePercent"
      | "setPointsPerBetUnit"
      | "toggleUserCreation"
      | "totalFeesAccumulated"
      | "transferOwnership"
      | "unpause"
      | "userCreationEnabled"
      | "userPoints"
      | "validateAndCancelDuel"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArenaEligibilitySet"
      | "ArenaEligibleBet"
      | "BetPlaced"
      | "DuelCanceled"
      | "DuelCreated"
      | "DuelCreationFeeUpdated"
      | "DuelResolved"
      | "FeesWithdrawn"
      | "GainsClaimed"
      | "GasAdvanced"
      | "GasDebtRepaid"
      | "ModeratorSet"
      | "OwnershipTransferred"
      | "Paused"
      | "PointsAwarded"
      | "PointsDeducted"
      | "PointsEarned"
      | "RefundIssued"
      | "ResolutionProposed"
      | "ResolverAuthorized"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ARENA_ACTIVATION_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_USER_DEADLINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POINTS_PER_DUEL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLUTION_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateArenaWithPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminCreateDuel",
    values: [string, string, boolean, [string, string, string], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeResolver",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedResolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bettingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bettingTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePotentialGains",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canActivateArena",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimGains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDuel",
    values: [string, string, [string, string, string], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duelArenaEligible",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duelCreationFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "duels", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeResolution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fanToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fanTokenBalanceSnapshot",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fanTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fanTokenThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasAdvanceFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasFeeDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gasRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBettingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDuelInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFanToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGasFeeDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutcomePot",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBets",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDuelBalanced",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "manualGasRepayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moderators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDuelId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingResolutions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pointsPerBetUnit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeResolution",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setArenaEligible",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDuelCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFanTokenThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasAdvanceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setModerator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPointsPerBetUnit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleUserCreation",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userCreationEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndCancelDuel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ARENA_ACTIVATION_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_USER_DEADLINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POINTS_PER_DUEL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLUTION_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateArenaWithPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminCreateDuel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bettingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bettingTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePotentialGains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canActivateArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimGains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDuel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "duelArenaEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "duelCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "duels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fanToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fanTokenBalanceSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fanTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fanTokenThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasAdvanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasFeeDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBettingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDuelInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFanToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasFeeDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutcomePot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDuelBalanced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualGasRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moderators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextDuelId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingResolutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsPerBetUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setArenaEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDuelCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFanTokenThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasAdvanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setModerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPointsPerBetUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleUserCreation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCreationEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateAndCancelDuel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace ArenaEligibilitySetEvent {
  export type InputTuple = [duelId: BigNumberish, eligible: boolean];
  export type OutputTuple = [duelId: bigint, eligible: boolean];
  export interface OutputObject {
    duelId: bigint;
    eligible: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArenaEligibleBetEvent {
  export type InputTuple = [user: AddressLike, duelId: BigNumberish];
  export type OutputTuple = [user: string, duelId: bigint];
  export interface OutputObject {
    user: string;
    duelId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    outcomeId: BigNumberish,
    amount: BigNumberish,
    fanTokenBalance: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    user: string,
    outcomeId: bigint,
    amount: bigint,
    fanTokenBalance: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    outcomeId: bigint;
    amount: bigint;
    fanTokenBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCanceledEvent {
  export type InputTuple = [duelId: BigNumberish];
  export type OutputTuple = [duelId: bigint];
  export interface OutputObject {
    duelId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCreatedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    creator: AddressLike,
    title: string,
    category: string,
    outcomes: [string, string, string],
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    creator: string,
    title: string,
    category: string,
    outcomes: [string, string, string],
    deadline: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    creator: string;
    title: string;
    category: string;
    outcomes: [string, string, string];
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCreationFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelResolvedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    winningOutcomeId: BigNumberish
  ];
  export type OutputTuple = [duelId: bigint, winningOutcomeId: bigint];
  export interface OutputObject {
    duelId: bigint;
    winningOutcomeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GainsClaimedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    bonus: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    user: string,
    amount: bigint,
    bonus: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    amount: bigint;
    bonus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasAdvancedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasDebtRepaidEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModeratorSetEvent {
  export type InputTuple = [moderator: AddressLike, status: boolean];
  export type OutputTuple = [moderator: string, status: boolean];
  export interface OutputObject {
    moderator: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsAwardedEvent {
  export type InputTuple = [
    user: AddressLike,
    points: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, points: bigint, reason: string];
  export interface OutputObject {
    user: string;
    points: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsDeductedEvent {
  export type InputTuple = [
    user: AddressLike,
    points: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, points: bigint, reason: string];
  export interface OutputObject {
    user: string;
    points: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsEarnedEvent {
  export type InputTuple = [
    user: AddressLike,
    duelId: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [user: string, duelId: bigint, points: bigint];
  export interface OutputObject {
    user: string;
    duelId: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [duelId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionProposedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    winningOutcomeId: BigNumberish,
    executeAt: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    winningOutcomeId: bigint,
    executeAt: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    winningOutcomeId: bigint;
    executeAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverAuthorizedEvent {
  export type InputTuple = [resolver: AddressLike, authorized: boolean];
  export type OutputTuple = [resolver: string, authorized: boolean];
  export interface OutputObject {
    resolver: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleDuel extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleDuel;
  waitForDeployment(): Promise<this>;

  interface: SimpleDuelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ARENA_ACTIVATION_POINTS: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  MAX_USER_DEADLINE: TypedContractMethod<[], [bigint], "view">;

  POINTS_PER_DUEL: TypedContractMethod<[], [bigint], "view">;

  RESOLUTION_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  activateArenaWithPoints: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminCreateDuel: TypedContractMethod<
    [
      _title: string,
      _category: string,
      _arenaEligible: boolean,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  authorizeResolver: TypedContractMethod<
    [_resolver: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;

  authorizedResolvers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  bettingToken: TypedContractMethod<[], [string], "view">;

  bettingTokenDecimals: TypedContractMethod<[], [bigint], "view">;

  calculatePotentialGains: TypedContractMethod<
    [_duelId: BigNumberish, _user: AddressLike],
    [[bigint, bigint] & { baseGains: bigint; bonusGains: bigint }],
    "view"
  >;

  canActivateArena: TypedContractMethod<
    [_user: AddressLike],
    [boolean],
    "view"
  >;

  claimGains: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDuel: TypedContractMethod<
    [
      _title: string,
      _category: string,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  duelArenaEligible: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  duelCreationFee: TypedContractMethod<[], [bigint], "view">;

  duels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        title: string;
        category: string;
        deprecated_arenaEligible: boolean;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        potTotal: bigint;
        feesCollected: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeResolution: TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fanToken: TypedContractMethod<[], [string], "view">;

  fanTokenBalanceSnapshot: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  fanTokenDecimals: TypedContractMethod<[], [bigint], "view">;

  fanTokenThreshold: TypedContractMethod<[], [bigint], "view">;

  gasAdvanceFee: TypedContractMethod<[], [bigint], "view">;

  gasFeeDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  gasRelayer: TypedContractMethod<[], [string], "view">;

  getBettingToken: TypedContractMethod<[], [string], "view">;

  getDuelInfo: TypedContractMethod<
    [_duelId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        [string, string, string],
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        string
      ] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        outcomes: [string, string, string];
        potTotal: bigint;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  getFanToken: TypedContractMethod<[], [string], "view">;

  getGasFeeDebt: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  getOutcomePot: TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish],
    [bigint],
    "view"
  >;

  getPlatformFeePercent: TypedContractMethod<[], [bigint], "view">;

  getUserBets: TypedContractMethod<
    [_duelId: BigNumberish, _user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getUserPoints: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  isDuelBalanced: TypedContractMethod<
    [_duelId: BigNumberish],
    [boolean],
    "view"
  >;

  manualGasRepayment: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  moderators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  nextDuelId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingResolutions: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  placeBet: TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  pointsPerBetUnit: TypedContractMethod<[], [bigint], "view">;

  proposeResolution: TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setArenaEligible: TypedContractMethod<
    [_duelId: BigNumberish, _eligible: boolean],
    [void],
    "nonpayable"
  >;

  setDuelCreationFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFanTokenThreshold: TypedContractMethod<
    [_newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasAdvanceFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  setModerator: TypedContractMethod<
    [_moderator: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFeePercent: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPointsPerBetUnit: TypedContractMethod<
    [_newPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleUserCreation: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  totalFeesAccumulated: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userCreationEnabled: TypedContractMethod<[], [boolean], "view">;

  userPoints: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  validateAndCancelDuel: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ARENA_ACTIVATION_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_USER_DEADLINE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POINTS_PER_DUEL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLUTION_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateArenaWithPoints"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminCreateDuel"
  ): TypedContractMethod<
    [
      _title: string,
      _category: string,
      _arenaEligible: boolean,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeResolver"
  ): TypedContractMethod<
    [_resolver: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedResolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bettingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bettingTokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePotentialGains"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _user: AddressLike],
    [[bigint, bigint] & { baseGains: bigint; bonusGains: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "canActivateArena"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimGains"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDuel"
  ): TypedContractMethod<
    [
      _title: string,
      _category: string,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "duelArenaEligible"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "duelCreationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "duels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        title: string;
        category: string;
        deprecated_arenaEligible: boolean;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        potTotal: bigint;
        feesCollected: bigint;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeResolution"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fanToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fanTokenBalanceSnapshot"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fanTokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fanTokenThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasAdvanceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasFeeDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasRelayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBettingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDuelInfo"
  ): TypedContractMethod<
    [_duelId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        [string, string, string],
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        string
      ] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        outcomes: [string, string, string];
        potTotal: bigint;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFanToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGasFeeDebt"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOutcomePot"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBets"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPoints"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isDuelBalanced"
  ): TypedContractMethod<[_duelId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "manualGasRepayment"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moderators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextDuelId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingResolutions"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pointsPerBetUnit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeResolution"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setArenaEligible"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _eligible: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDuelCreationFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFanTokenThreshold"
  ): TypedContractMethod<[_newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasAdvanceFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setModerator"
  ): TypedContractMethod<
    [_moderator: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFeePercent"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPointsPerBetUnit"
  ): TypedContractMethod<[_newPoints: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleUserCreation"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesAccumulated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCreationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "userPoints"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "validateAndCancelDuel"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArenaEligibilitySet"
  ): TypedContractEvent<
    ArenaEligibilitySetEvent.InputTuple,
    ArenaEligibilitySetEvent.OutputTuple,
    ArenaEligibilitySetEvent.OutputObject
  >;
  getEvent(
    key: "ArenaEligibleBet"
  ): TypedContractEvent<
    ArenaEligibleBetEvent.InputTuple,
    ArenaEligibleBetEvent.OutputTuple,
    ArenaEligibleBetEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "DuelCanceled"
  ): TypedContractEvent<
    DuelCanceledEvent.InputTuple,
    DuelCanceledEvent.OutputTuple,
    DuelCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DuelCreated"
  ): TypedContractEvent<
    DuelCreatedEvent.InputTuple,
    DuelCreatedEvent.OutputTuple,
    DuelCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DuelCreationFeeUpdated"
  ): TypedContractEvent<
    DuelCreationFeeUpdatedEvent.InputTuple,
    DuelCreationFeeUpdatedEvent.OutputTuple,
    DuelCreationFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DuelResolved"
  ): TypedContractEvent<
    DuelResolvedEvent.InputTuple,
    DuelResolvedEvent.OutputTuple,
    DuelResolvedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "GainsClaimed"
  ): TypedContractEvent<
    GainsClaimedEvent.InputTuple,
    GainsClaimedEvent.OutputTuple,
    GainsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GasAdvanced"
  ): TypedContractEvent<
    GasAdvancedEvent.InputTuple,
    GasAdvancedEvent.OutputTuple,
    GasAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "GasDebtRepaid"
  ): TypedContractEvent<
    GasDebtRepaidEvent.InputTuple,
    GasDebtRepaidEvent.OutputTuple,
    GasDebtRepaidEvent.OutputObject
  >;
  getEvent(
    key: "ModeratorSet"
  ): TypedContractEvent<
    ModeratorSetEvent.InputTuple,
    ModeratorSetEvent.OutputTuple,
    ModeratorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PointsAwarded"
  ): TypedContractEvent<
    PointsAwardedEvent.InputTuple,
    PointsAwardedEvent.OutputTuple,
    PointsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "PointsDeducted"
  ): TypedContractEvent<
    PointsDeductedEvent.InputTuple,
    PointsDeductedEvent.OutputTuple,
    PointsDeductedEvent.OutputObject
  >;
  getEvent(
    key: "PointsEarned"
  ): TypedContractEvent<
    PointsEarnedEvent.InputTuple,
    PointsEarnedEvent.OutputTuple,
    PointsEarnedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionProposed"
  ): TypedContractEvent<
    ResolutionProposedEvent.InputTuple,
    ResolutionProposedEvent.OutputTuple,
    ResolutionProposedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverAuthorized"
  ): TypedContractEvent<
    ResolverAuthorizedEvent.InputTuple,
    ResolverAuthorizedEvent.OutputTuple,
    ResolverAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ArenaEligibilitySet(uint256,bool)": TypedContractEvent<
      ArenaEligibilitySetEvent.InputTuple,
      ArenaEligibilitySetEvent.OutputTuple,
      ArenaEligibilitySetEvent.OutputObject
    >;
    ArenaEligibilitySet: TypedContractEvent<
      ArenaEligibilitySetEvent.InputTuple,
      ArenaEligibilitySetEvent.OutputTuple,
      ArenaEligibilitySetEvent.OutputObject
    >;

    "ArenaEligibleBet(address,uint256)": TypedContractEvent<
      ArenaEligibleBetEvent.InputTuple,
      ArenaEligibleBetEvent.OutputTuple,
      ArenaEligibleBetEvent.OutputObject
    >;
    ArenaEligibleBet: TypedContractEvent<
      ArenaEligibleBetEvent.InputTuple,
      ArenaEligibleBetEvent.OutputTuple,
      ArenaEligibleBetEvent.OutputObject
    >;

    "BetPlaced(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "DuelCanceled(uint256)": TypedContractEvent<
      DuelCanceledEvent.InputTuple,
      DuelCanceledEvent.OutputTuple,
      DuelCanceledEvent.OutputObject
    >;
    DuelCanceled: TypedContractEvent<
      DuelCanceledEvent.InputTuple,
      DuelCanceledEvent.OutputTuple,
      DuelCanceledEvent.OutputObject
    >;

    "DuelCreated(uint256,address,string,string,string[3],uint256)": TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;
    DuelCreated: TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;

    "DuelCreationFeeUpdated(uint256)": TypedContractEvent<
      DuelCreationFeeUpdatedEvent.InputTuple,
      DuelCreationFeeUpdatedEvent.OutputTuple,
      DuelCreationFeeUpdatedEvent.OutputObject
    >;
    DuelCreationFeeUpdated: TypedContractEvent<
      DuelCreationFeeUpdatedEvent.InputTuple,
      DuelCreationFeeUpdatedEvent.OutputTuple,
      DuelCreationFeeUpdatedEvent.OutputObject
    >;

    "DuelResolved(uint256,uint256)": TypedContractEvent<
      DuelResolvedEvent.InputTuple,
      DuelResolvedEvent.OutputTuple,
      DuelResolvedEvent.OutputObject
    >;
    DuelResolved: TypedContractEvent<
      DuelResolvedEvent.InputTuple,
      DuelResolvedEvent.OutputTuple,
      DuelResolvedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "GainsClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      GainsClaimedEvent.InputTuple,
      GainsClaimedEvent.OutputTuple,
      GainsClaimedEvent.OutputObject
    >;
    GainsClaimed: TypedContractEvent<
      GainsClaimedEvent.InputTuple,
      GainsClaimedEvent.OutputTuple,
      GainsClaimedEvent.OutputObject
    >;

    "GasAdvanced(address,uint256)": TypedContractEvent<
      GasAdvancedEvent.InputTuple,
      GasAdvancedEvent.OutputTuple,
      GasAdvancedEvent.OutputObject
    >;
    GasAdvanced: TypedContractEvent<
      GasAdvancedEvent.InputTuple,
      GasAdvancedEvent.OutputTuple,
      GasAdvancedEvent.OutputObject
    >;

    "GasDebtRepaid(address,uint256)": TypedContractEvent<
      GasDebtRepaidEvent.InputTuple,
      GasDebtRepaidEvent.OutputTuple,
      GasDebtRepaidEvent.OutputObject
    >;
    GasDebtRepaid: TypedContractEvent<
      GasDebtRepaidEvent.InputTuple,
      GasDebtRepaidEvent.OutputTuple,
      GasDebtRepaidEvent.OutputObject
    >;

    "ModeratorSet(address,bool)": TypedContractEvent<
      ModeratorSetEvent.InputTuple,
      ModeratorSetEvent.OutputTuple,
      ModeratorSetEvent.OutputObject
    >;
    ModeratorSet: TypedContractEvent<
      ModeratorSetEvent.InputTuple,
      ModeratorSetEvent.OutputTuple,
      ModeratorSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PointsAwarded(address,uint256,string)": TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
    PointsAwarded: TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;

    "PointsDeducted(address,uint256,string)": TypedContractEvent<
      PointsDeductedEvent.InputTuple,
      PointsDeductedEvent.OutputTuple,
      PointsDeductedEvent.OutputObject
    >;
    PointsDeducted: TypedContractEvent<
      PointsDeductedEvent.InputTuple,
      PointsDeductedEvent.OutputTuple,
      PointsDeductedEvent.OutputObject
    >;

    "PointsEarned(address,uint256,uint256)": TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;
    PointsEarned: TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;

    "RefundIssued(uint256,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;

    "ResolutionProposed(uint256,uint256,uint256)": TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;
    ResolutionProposed: TypedContractEvent<
      ResolutionProposedEvent.InputTuple,
      ResolutionProposedEvent.OutputTuple,
      ResolutionProposedEvent.OutputObject
    >;

    "ResolverAuthorized(address,bool)": TypedContractEvent<
      ResolverAuthorizedEvent.InputTuple,
      ResolverAuthorizedEvent.OutputTuple,
      ResolverAuthorizedEvent.OutputObject
    >;
    ResolverAuthorized: TypedContractEvent<
      ResolverAuthorizedEvent.InputTuple,
      ResolverAuthorizedEvent.OutputTuple,
      ResolverAuthorizedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
