/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleDuel__factory } from "./SimpleDuel__factory";
export { SimpleDuelSecure__factory } from "./SimpleDuelSecure__factory";
