/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SimpleDuelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arenas"
      | "bettingToken"
      | "claimGains"
      | "claimRefund"
      | "createDuel"
      | "duels"
      | "fanToken"
      | "fanTokenDecimals"
      | "fanTokenThreshold"
      | "getBettingToken"
      | "getFanToken"
      | "getOutcomePot"
      | "getPlatformFeePercent"
      | "nextArenaId"
      | "nextDuelId"
      | "owner"
      | "placeBet"
      | "platformFeePercent"
      | "pointsPerBetUnit"
      | "renounceOwnership"
      | "resolveDuel"
      | "transferOwnership"
      | "validateAndCancelDuel"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArenaEligibleBet"
      | "BetPlaced"
      | "DuelCanceled"
      | "DuelCreated"
      | "DuelResolved"
      | "GainsClaimed"
      | "OwnershipTransferred"
      | "PointsEarned"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "arenas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bettingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimGains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDuel",
    values: [string, string, boolean, [string, string, string], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "duels", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "fanToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fanTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fanTokenThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBettingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFanToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOutcomePot",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextArenaId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextDuelId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pointsPerBetUnit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDuel",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndCancelDuel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "arenas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bettingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimGains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDuel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fanToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fanTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fanTokenThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBettingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFanToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutcomePot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextArenaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextDuelId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pointsPerBetUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDuel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndCancelDuel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace ArenaEligibleBetEvent {
  export type InputTuple = [user: AddressLike, duelId: BigNumberish];
  export type OutputTuple = [user: string, duelId: bigint];
  export interface OutputObject {
    user: string;
    duelId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    outcomeId: BigNumberish,
    amount: BigNumberish,
    fanTokenBalance: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    user: string,
    outcomeId: bigint,
    amount: bigint,
    fanTokenBalance: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    outcomeId: bigint;
    amount: bigint;
    fanTokenBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCanceledEvent {
  export type InputTuple = [duelId: BigNumberish];
  export type OutputTuple = [duelId: bigint];
  export interface OutputObject {
    duelId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelCreatedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    title: string,
    category: string,
    arenaEligible: boolean,
    outcomes: [string, string, string],
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    duelId: bigint,
    title: string,
    category: string,
    arenaEligible: boolean,
    outcomes: [string, string, string],
    deadline: bigint
  ];
  export interface OutputObject {
    duelId: bigint;
    title: string;
    category: string;
    arenaEligible: boolean;
    outcomes: [string, string, string];
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DuelResolvedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    winningOutcomeId: BigNumberish
  ];
  export type OutputTuple = [duelId: bigint, winningOutcomeId: bigint];
  export interface OutputObject {
    duelId: bigint;
    winningOutcomeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GainsClaimedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [duelId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsEarnedEvent {
  export type InputTuple = [
    user: AddressLike,
    duelId: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [user: string, duelId: bigint, points: bigint];
  export interface OutputObject {
    user: string;
    duelId: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    duelId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [duelId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    duelId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleDuel extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleDuel;
  waitForDeployment(): Promise<this>;

  interface: SimpleDuelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arenas: TypedContractMethod<
    [_duelId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        [string, string, string],
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        outcomes: [string, string, string];
        potTotal: bigint;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
      }
    ],
    "view"
  >;

  bettingToken: TypedContractMethod<[], [string], "view">;

  claimGains: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDuel: TypedContractMethod<
    [
      _title: string,
      _category: string,
      _arenaEligible: boolean,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  duels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, boolean, boolean, bigint, bigint] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        potTotal: bigint;
      }
    ],
    "view"
  >;

  fanToken: TypedContractMethod<[], [string], "view">;

  fanTokenDecimals: TypedContractMethod<[], [bigint], "view">;

  fanTokenThreshold: TypedContractMethod<[], [bigint], "view">;

  getBettingToken: TypedContractMethod<[], [string], "view">;

  getFanToken: TypedContractMethod<[], [string], "view">;

  getOutcomePot: TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish],
    [bigint],
    "view"
  >;

  getPlatformFeePercent: TypedContractMethod<[], [bigint], "view">;

  nextArenaId: TypedContractMethod<[], [bigint], "view">;

  nextDuelId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  pointsPerBetUnit: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDuel: TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validateAndCancelDuel: TypedContractMethod<
    [_duelId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arenas"
  ): TypedContractMethod<
    [_duelId: BigNumberish],
    [
      [
        string,
        string,
        boolean,
        [string, string, string],
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        outcomes: [string, string, string];
        potTotal: bigint;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bettingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimGains"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDuel"
  ): TypedContractMethod<
    [
      _title: string,
      _category: string,
      _arenaEligible: boolean,
      _outcomes: [string, string, string],
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "duels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, boolean, boolean, bigint, bigint] & {
        title: string;
        category: string;
        arenaEligible: boolean;
        deadline: bigint;
        isResolved: boolean;
        isCanceled: boolean;
        winningOutcomeId: bigint;
        potTotal: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fanToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fanTokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fanTokenThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBettingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFanToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOutcomePot"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextArenaId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextDuelId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _outcomeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pointsPerBetUnit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDuel"
  ): TypedContractMethod<
    [_duelId: BigNumberish, _winningOutcomeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateAndCancelDuel"
  ): TypedContractMethod<[_duelId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ArenaEligibleBet"
  ): TypedContractEvent<
    ArenaEligibleBetEvent.InputTuple,
    ArenaEligibleBetEvent.OutputTuple,
    ArenaEligibleBetEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "DuelCanceled"
  ): TypedContractEvent<
    DuelCanceledEvent.InputTuple,
    DuelCanceledEvent.OutputTuple,
    DuelCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DuelCreated"
  ): TypedContractEvent<
    DuelCreatedEvent.InputTuple,
    DuelCreatedEvent.OutputTuple,
    DuelCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DuelResolved"
  ): TypedContractEvent<
    DuelResolvedEvent.InputTuple,
    DuelResolvedEvent.OutputTuple,
    DuelResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GainsClaimed"
  ): TypedContractEvent<
    GainsClaimedEvent.InputTuple,
    GainsClaimedEvent.OutputTuple,
    GainsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PointsEarned"
  ): TypedContractEvent<
    PointsEarnedEvent.InputTuple,
    PointsEarnedEvent.OutputTuple,
    PointsEarnedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "ArenaEligibleBet(address,uint256)": TypedContractEvent<
      ArenaEligibleBetEvent.InputTuple,
      ArenaEligibleBetEvent.OutputTuple,
      ArenaEligibleBetEvent.OutputObject
    >;
    ArenaEligibleBet: TypedContractEvent<
      ArenaEligibleBetEvent.InputTuple,
      ArenaEligibleBetEvent.OutputTuple,
      ArenaEligibleBetEvent.OutputObject
    >;

    "BetPlaced(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "DuelCanceled(uint256)": TypedContractEvent<
      DuelCanceledEvent.InputTuple,
      DuelCanceledEvent.OutputTuple,
      DuelCanceledEvent.OutputObject
    >;
    DuelCanceled: TypedContractEvent<
      DuelCanceledEvent.InputTuple,
      DuelCanceledEvent.OutputTuple,
      DuelCanceledEvent.OutputObject
    >;

    "DuelCreated(uint256,string,string,bool,string[3],uint256)": TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;
    DuelCreated: TypedContractEvent<
      DuelCreatedEvent.InputTuple,
      DuelCreatedEvent.OutputTuple,
      DuelCreatedEvent.OutputObject
    >;

    "DuelResolved(uint256,uint256)": TypedContractEvent<
      DuelResolvedEvent.InputTuple,
      DuelResolvedEvent.OutputTuple,
      DuelResolvedEvent.OutputObject
    >;
    DuelResolved: TypedContractEvent<
      DuelResolvedEvent.InputTuple,
      DuelResolvedEvent.OutputTuple,
      DuelResolvedEvent.OutputObject
    >;

    "GainsClaimed(uint256,address,uint256)": TypedContractEvent<
      GainsClaimedEvent.InputTuple,
      GainsClaimedEvent.OutputTuple,
      GainsClaimedEvent.OutputObject
    >;
    GainsClaimed: TypedContractEvent<
      GainsClaimedEvent.InputTuple,
      GainsClaimedEvent.OutputTuple,
      GainsClaimedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PointsEarned(address,uint256,uint256)": TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;
    PointsEarned: TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;

    "RefundIssued(uint256,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
